name:                typed-webdriver
version:             0.1.0.0
github:              "yigitozkavci/typed-webdriver"
license:             BSD3
author:              "Yigit Ozkavci"
maintainer:          "yigitozkavci8@gmail.com"
copyright:           "2017 Yigit Ozkavci"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yigitozkavci/typed-webdriver#readme>

dependencies:
- base >= 4.7 && < 5

library:
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  - -Wall
  dependencies:
    - webdriver
    - template-haskell
    - aeson
    - reflection
    - text
    - hxt-xpath
    - pretty-simple
  source-dirs: src

executables:
  typed-webdriver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-webdriver

tests:
  typed-webdriver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-webdriver
